### ISSUE TITLE
Some functions could be reused between plugins

### ISSUE THREAD

**Issue by Txiaozhe** [alibaba/pipcook#115]
There some functions could be reused between plugins, e.g.:
```js
function MakeWordsSet(words_file: string): Promise<Set<string>> {
...
}
```
this 'MakeWordsSet' in plugin model-define and model-evaluate are same and it can be reused.
So could we build a mechanism for reuse that same function between plugins?

**Comment by Txiaozhe** [comment]
There are many more functions like this, rewrite these is waste :(

**Comment by yorkie** [comment]
Good idea, this is why we will have https://github.com/alibaba/pipcook/pull/75, we have Plugin Runtime and Plugin API for plugin developers.

**Comment by yorkie** [comment]
And developers is also free to share these function in NPM, Plugin Runtime will be based on Node.js and NPM.

**Comment by Txiaozhe** [comment]
enen, LGTM~ It will be better! :)

**Comment by FeelyChau** [comment]
Plugins has instead by scripts, see https://alibaba.github.io/pipcook/#/contributing/contribute-a-script
