### ISSUE TITLE
cli: rewrite in TypeScript

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#135]
Pipcook is using TypeScript to write our core, builtin plugins and tools, to keep the consistence of source code, it's great to use TypeScript for our cli, too.

If you are familiar with TypeScript, feel free to help us with this :)

**Comment by yorkie** [comment]
@Txiaozhe Feel free to open a new PR for this issue, I can't assign the task to you because you are still not in our collaborators list.

**Comment by Txiaozhe** [comment]
OO, I will still do this :(
