### ISSUE TITLE
install: pipcook init --tuna throw error

### ISSUE THREAD

**Issue by sinoon** [alibaba/pipcook#144]
When I follow the doc, got an error:

```
pipcook init --tuna    
error: unknown option '--tuna'
```

in the document, however, show the usage

![image](https://user-images.githubusercontent.com/6065488/80471576-2cdc4200-8976-11ea-84e3-9ce7105da9ce.png)

**Comment by utkobe** [comment]
We have not published the cli version with tuna option. You could either just remove tuna option for now or clone the github repo and build from source codes.

**Comment by yorkie** [comment]
Maybe we need versions for our documentation.
