### ISSUE TITLE
boa: the boa object cannot be stringfied

### ISSUE THREAD

**Issue by utkobe** [alibaba/pipcook#146]
Boa python wrapper object cannot be converted to string using JSON.stringify. It's good to support this transformation or provide a method like .toJson() to easily convert to JS native object.

For example

```js
const boa = require('../packages/boa');
const np = boa.import('numpy');
const obj = np.array([1,2,3]);
console.log(JSON.stringify(obj));
```

The above codes will throw error

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '__handle__' -> object with constructor 'boa.Object'
    --- property '__wrapped__' closes the circle
    at JSON.stringify (<anonymous>)
```

**Comment by yorkie** [comment]
We can implement the [`toJSON()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior) for Python wrapped objects.
