### ISSUE TITLE
meta: release lifecycle

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#15]
The following are the questions associated with the release lifecycle and my answers:

> Time-based or feature-based release?

Pipcook uses semver for release management, so the release generally refers to Major, Minor, and Patch.

For the **major** versions, time-based release is often after the software and ecosystem are relatively mature, so major will use feature-based. Each major version often needs to define the features of that version first, and then define the milestones to complete.

For the **minor** version, under the major version target is basically determined, the iteration period could be relatively fixed, so it can be time-based. Therefore, we can define a minor version as 2 weeks and an even number as stable.

For the **patch** version, it basically fixes the existing versions, so it needs to be divided into different situations to discuss. For the latest version (such as 0.7.x), we can decide whether to release it based on whether there are daily bugfixes. For historical versions (such as 0.3.x, 0.4.x), we need to determine the severity of the bug, the relevance of the project, and community feedback to operate manually.

> Provide LTS(long term support) version

No, need to wait until the software matures, currently there is not enough people to maintain, but can provide patches for a specific version range.

> Release automatically

Major: release maintainer, minor: release maintainer, patch: ci + release maintainer

@utkobe @wordcount Feel free to create new question and give your answers :)

**Comment by utkobe** [comment]
this looks good to me. @yorkie.

**Comment by yorkie** [comment]
And there are some requirements to be done before we apply this:

- The CI/CD **MUST** be working to valid the automatic release.
- new labels **MUST** be added for automatic release: `major`, `minor`, `patch`.

**Comment by yorkie** [comment]
Closing this because this is merged at #27.
