### ISSUE TITLE
meta: nominate Jim Tang as our first outside collaborator

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#165]
@Txiaozhe contributed a lot of important parts includes:

- migration from Python-based model define plugin to JavaScript-based.
- rewrite our CLI in TypeScript.

And there are too much other [commits](https://github.com/alibaba/pipcook/commits?author=Txiaozhe) who did contribute, therefore I am here to nominate him as our first outside collaborator.

Because this is our first nomination for outside collaborators, we need the LGTMs of all collaborators, and also include the consent of @shadowkun.

/cc @utkobe @wordcount

**Comment by shadowkun** [comment]
LGTM

**Comment by Txiaozhe** [comment]
Thanks~ @yorkie @shadowkun and all of others.

**Comment by utkobe** [comment]
LGTM :)

**Comment by Txiaozhe** [comment]
Thanks @utkobe :)

**Comment by wordcount** [comment]
LGTM :)

**Comment by yorkie** [comment]
Invited, @Txiaozhe May I ask you to please accept invitation on https://github.com/alibaba/pipcook/invitations?

**Comment by Txiaozhe** [comment]
Thanks @wordcount and all of others.  And I have accepted:) @yorkie  Thanks~
