### ISSUE TITLE
meta: will Deno be used in pipcook?

### ISSUE THREAD

**Issue by Txiaozhe** [alibaba/pipcook#172]
deno was released v1.0.0-rc1 in:
https://github.com/denoland/deno/releases

There are most of code of pipcook is wrote by typescript, so will we use deno in pipcook for native support for typescript?

**Comment by yorkie** [comment]
Node.js or Deno for Pipcook Daemon doesn't make too much sense, it's just an executable on user-land. However we still have the following parts to run on Deno:

- MLApp, it's actually in native TypeScript.
- Plugin Runtime:
  - how to run `@pipcook/boa`? N-API should be supported by Deno or rewrite boa in Deno's addon?
  - how to run tensorflow.js?

**Comment by yorkie** [comment]
> how to run @pipcook/boa? N-API should be supported by Deno or rewrite boa in Deno's addon?

As @ry has commented on https://github.com/denoland/deno/issues/1654#issuecomment-459950528, WASM is the security way instead of [native extensions](https://github.com/denoland/deno/pull/3372), so I'm to stand on integrating Boa on WASM hence that it could be ran in Browser.
