### ISSUE TITLE
boa: use Node.js custom loader for better import-statement

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#173]
See Node.js [ESM Experiment Loaders](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_experimental_loaders), we could define a custom loader for Python modules just like:

```js
// node --experiment @pipcook/boa/esm/loader.mjs app.js
import { list, tuple } from 'py:builtins';
import { Image, ImageDraw } from 'py:PIL';
import { DBSCAN } from 'py:sklearn.cluster';
import { word2vec } from 'py:gensim.models';
```
Any good suggestion for the import name pattern?

**Comment by Txiaozhe** [comment]
But this hook is experimental:( May we use it later?

**Comment by yorkie** [comment]
> But this hook is experimental:( May we use it later?

The loader script is separated, so that's free to add.

**Comment by Txiaozhe** [comment]
> > But this hook is experimental:( May we use it later?
> 
> The loader script is separated, so that's free to add.

Looks good~

**Comment by rickyes** [comment]
Hi, I've been looking into trying to add `ESM` support for `Boa` lately and this might be something I can help with.
