### ISSUE TITLE
cli: pipcook npm/cnpm install node_modules failed

### ISSUE THREAD

**Issue by Heluwe** [alibaba/pipcook#184]
> git clone git@github.com:alibaba/pipcook.git
> npm/cnpm install

Npm install result:
![image](https://user-images.githubusercontent.com/7344340/81466918-bd811080-9207-11ea-8af1-deb0e61b10fe.png)

Npm log below:
> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global-style' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose npm-session 33fe36861955ab8e
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall @pipcook/plugins-bayesian-model-evaluate@0.5.10
7 info lifecycle @pipcook/plugins-bayesian-model-evaluate@0.5.10~preinstall: @pipcook/plugins-bayesian-model-evaluate@0.5.10
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 31ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 9ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 9ms
18 timing stage:loadIdealTree Completed in 21ms
19 silly currentTree @pipcook/plugins-bayesian-model-evaluate@0.5.10
20 silly idealTree @pipcook/plugins-bayesian-model-evaluate@0.5.10
20 silly idealTree └── @types/jasmine@3.5.10
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 58ms
23 silly diffTrees action count 1
24 silly diffTrees add @types/jasmine@3.5.10
25 silly decomposeActions action count 8
26 silly decomposeActions fetch @types/jasmine@3.5.10
27 silly decomposeActions extract @types/jasmine@3.5.10
28 silly decomposeActions preinstall @types/jasmine@3.5.10
29 silly decomposeActions build @types/jasmine@3.5.10
30 silly decomposeActions install @types/jasmine@3.5.10
31 silly decomposeActions postinstall @types/jasmine@3.5.10
32 silly decomposeActions finalize @types/jasmine@3.5.10
33 silly decomposeActions refresh-package-json @types/jasmine@3.5.10
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir /Users/xly/.npminstall_tarball/_locks correctMkdir not in flight; initializing
37 timing stage:rollbackFailedOptional Completed in 1ms
38 timing stage:runTopLevelLifecycles Completed in 373ms
39 silly saveTree @pipcook/plugins-bayesian-model-evaluate@0.5.10
39 silly saveTree └── @types/jasmine@3.5.10
40 warn @pipcook/plugins-bayesian-model-evaluate@0.5.10 No description
41 warn @pipcook/plugins-bayesian-model-evaluate@0.5.10 No repository field.
42 verbose stack Error: ENOENT: no such file or directory, lchown '/Users/xly/.npminstall_tarball/_locks/staging-9e71599999f623f6.lock'
43 verbose cwd /Users/xly/Desktop/comp/pipcook/packages/plugins/model-evaluate/bayesian-model-evaluate
44 verbose Darwin 19.3.0
45 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global-style"
46 verbose node v10.17.0
47 verbose npm  v6.11.3
48 error code ENOENT
49 error syscall lchown
50 error path /Users/xly/.npminstall_tarball/_locks/staging-9e71599999f623f6.lock
51 error errno -2
52 error enoent ENOENT: no such file or directory, lchown '/Users/xly/.npminstall_tarball/_locks/staging-9e71599999f623f6.lock'
53 error enoent This is related to npm not being able to find a file.
54 verbose exit [ -2, true ]

**Comment by yorkie** [comment]
@Heluwe Could you send your complete terminal outputs?

**Comment by FeelyChau** [comment]
@Heluwe If you have more information for this issue, please reopen it and put it on, for now, we need to close it.
