### ISSUE TITLE
core: may using enum for plugin type constant is better?

### ISSUE THREAD

**Issue by Txiaozhe** [alibaba/pipcook#189]
```ts
export type PluginTypeI = 'dataCollect' | 'dataAccess' | 'dataProcess' | 'modelLoad' | 'modelDefine' |'modelTrain' | 'modelEvaluate';
```

```ts
export const enum PluginTypeI {
  dataCollect = 'dataCollect',
  ...
}
```

**Comment by yorkie** [comment]
Could you please give more detailed reason for this change proposal?

**Comment by yorkie** [comment]
And I'm -1 on using enum, because it requires us to import the Enum object before using, but string-based type alias will not.

**Comment by Txiaozhe** [comment]
No more reason just 'enum' looks clearer and more accurate, I am not very certain this change so only launch an issue but not a pr.
If you also like this, I will do:)

**Comment by Txiaozhe** [comment]
> And I'm -1 on using enum, because it requires us to import the Enum object before using, but string-based type alias will not.

It is well-judged, too:)
