### ISSUE TITLE
meta: nominate Jory Liang as outside collaborator

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#193]
@liangzr contributed some specific [TypeScript related commits](https://github.com/alibaba/pipcook/commits?author=liangzr), and helped us review PR in TypeScript perspective.

Therefore I'm going to nominate him as one of outside collaborator & TypeScript reviewer. We need the approvals from the following collaborators: @utkobe @wordcount @Txiaozhe.

**Comment by Txiaozhe** [comment]
LGTM:)

**Comment by utkobe** [comment]
LGTM :)

**Comment by yorkie** [comment]
Done!
