### ISSUE TITLE
costa: check if boa is required for current pipeline

### ISSUE THREAD

**Issue by rickycao-qy** [alibaba/pipcook#227]
Boa will be built for every pipelines. However, we have pipelines that do not depend on any python libraries. Probably it's better to have a check here to speed up pipelines

**Comment by yorkie** [comment]
What do you mean by the "speed up" for? Installation or runtime?

**Comment by FeelyChau** [comment]
The `boa` has been removed into the framework package which is pre-build, and it's loaded dynamically.
