### ISSUE TITLE
pipcook run with  some problems,  ETIMEDOUT

### ISSUE THREAD

**Issue by Fay-Hu** [alibaba/pipcook#248]
The detial:
pipcook run ./example/pipelines/object-detection.json
✖ Error: connect ETIMEDOUT 104.16.20.35:80

![image](https://user-images.githubusercontent.com/13618408/84975711-ac0d1b80-b158-11ea-96d5-d933cfe5e786.png)

What shoud i do, please?

**Comment by yorkie** [comment]
Hi @Fay-Hu, how do you get the screenshot?

**Comment by Fay-Hu** [comment]
> Hi @Fay-Hu, how do you get the screenshot?

visit 104.16.20.35:80 on broswer

**Comment by yorkie** [comment]
And you can try `pipcook pipeline install ./example/object-detection.json` firstly to make sure if the plugin installation is ok.

**Comment by yorkie** [comment]
The 104.16.20.35 is one of ips for resolving `registry.npmjs.com`, may I ask you to try with: `pipcook pipeline install ./example/object-detection.json`?

**Comment by Fay-Hu** [comment]
![image](https://user-images.githubusercontent.com/13618408/84976431-681b1600-b15a-11ea-9845-c48764d396ac.png)
![image](https://user-images.githubusercontent.com/13618408/84976473-8b45c580-b15a-11ea-8432-0ab3a1233a6e.png)

then got `daemon is not started, run "pipcook daemon start"`

**Comment by yorkie** [comment]
Yea, make sure the daemon is up and try `pipcook run` again?

**Comment by Fay-Hu** [comment]
Thanks for your response, it's ok now.
