### ISSUE TITLE
boa: could we set a global switch for pypi?

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#259]
There are 2 way to switch pypi when install pipcook:
1. environment variable
2. pipcook command parameter `--tuna`

Could we prioritize environment variables with commands `--tuna` parameter, if so, we can define the environment variable and the pypi is changed.

**Comment by yorkie** [comment]
I cannot get what this issue is to talk about, @FeelyChau may I ask you to have more details to explain?

**Comment by FeelyChau** [comment]
I hope we can change pypi by setting the environment variable for every operation: `npm install` or `pipcook plugin install`.

**Comment by yorkie** [comment]
`--tuna` uses the environment variables like `BOA_TUNA`.

**Comment by FeelyChau** [comment]
I know that, but it's a little tedious. I hope to set once and effective everywhere

**Comment by yorkie** [comment]
Hmm, developers could use these environment variables, either.

**Comment by FeelyChau** [comment]
As I know, the environment variables can't be effective when execute `pipcook plugin install`.

**Comment by yorkie** [comment]
So it should not be labeled as "boa".

**Comment by FeelyChau** [comment]
OK, changed to `pipcook daemon`.

**Comment by FeelyChau** [comment]
Parameter `tuna` is not necessary for Pipcook v2. Should be closed.
