### ISSUE TITLE
cli: pipcook job log support real-time logs

### ISSUE THREAD

**Issue by lewis617** [alibaba/pipcook#308]

**Comment by yorkie** [comment]
@lewis617 I guess you are requesting the real-time logs for `pipcook job log`? We'll change it to use SSE for pushing logs to the terminal instead of `tail -f`, which is not supported when cli connected a daemon remotely.

**Comment by FeelyChau** [comment]
#408 This PR implemented the real time logs.

**Comment by FeelyChau** [comment]
Merged into master #405
