### ISSUE TITLE
costa: frequent timeout errors when running the CI tests

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#319]
The test case is https://github.com/alibaba/pipcook/blob/master/packages/costa/src/runnable_test.ts#L21-L24, timeout is 5000ms.

**Comment by FeelyChau** [comment]
When we fork a client process, the typescript from `client.ts` needs to be compiled, and takes too much time. so we run the js version now.

**Comment by yorkie** [comment]
It should get fixed at #327.
