### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/Users/xxx/pipcook-examp'

### ISSUE THREAD

**Issue by anyexinglu** [alibaba/pipcook#4]
![image](https://user-images.githubusercontent.com/8243326/71554778-d2ca7f00-2a5e-11ea-9013-af701dae5066.png)

拉到本地，按照readme启动后，执行`node examples/pipeline-databinding-image-classification.js`，一直不行，报错：

Error: ENOENT: no such file or directory, open '/Users/xx/xx/xx/pipcook-examp'

但目录里一直有 /Users/xx/xx/xx/pipcook-example/pipcook-project/examples/pipeline-databinding-image-classification.js 的，不知道为什么

**Comment by anyexinglu** [comment]
![image](https://user-images.githubusercontent.com/8243326/71554808-318ff880-2a5f-11ea-80c7-99a8f6afb446.png)

logs：

{"pipelineName":"pipeline-example-databinding-image-classification","pipelineVersion":"0.2.0","logDir":"/Users/yangxiayan/Documents/duoduo/pipcook-example/pipcook-project/.pipcook-log","pipelineId":"pipcook-pipeline-1577610335586","latestOriginSampleData":{"trainDataPath":"/Users/yangxiayan/Documents/duoduo/pipcook-example/pipcook-project/.pipcook-log/datasets/eCommerceImageClassification/annotations/train","validationDataPath":"/Users/yangxiayan/Documents/duoduo/pipcook-example/pipcook-project/.pipcook-log/datasets/eCommerceImageClassification/annotations/validation","testDataPath":"/Users/yangxiayan/Documents/duoduo/pipcook-example/pipcook-project/.pipcook-log/datasets/eCommerceImageClassification/annotations/test"},"latestSampleData":null,"latestModel":null,"latestEvaluateResult":null,"latestDeploymentResult":null,"fastify":{"log":{},"server":{"_events":{},"_eventsCount":4,"_connections":0,"_handle":null,"_usingWorkers":false,"_workers":[],"_unref":false,"allowHalfOpen":true,"pauseOnConnect":false,"httpAllowHalfOpen":false,"timeout":120000,"keepAliveTimeout":5000,"maxHeadersCount":null,"headersTimeout":40000},"initialConfig":{"requestIdHeader":"request-id","requestIdLogLabel":"reqId","disableRequestLogging":false,"bodyLimit":1048576,"caseSensitive":true,"ignoreTrailingSlash":false,"maxParamLength":100,"onProtoPoisoning":"error","onConstructorPoisoning":"ignore","pluginTimeout":10000}},"updatedType":"evaluate","components":[{"type":"dataCollect","previousComponent":null,"status":"success","returnType":"origindata","params":{"url":"http://ai-sample.oss-cn-hangzhou.aliyuncs.com/image_classification/datasets/eCommerceImageClassification.zip"}},{"type":"dataAccess","previousComponent":{"type":"dataCollect","previousComponent":null,"status":"success","returnType":"origindata","params":{"url":"http://ai-sample.oss-cn-hangzhou.aliyuncs.com/image_classification/datasets/eCommerceImageClassification.zip"}},"status":"not execute","returnType":"data","params":{"imgSize":[256,256]}},{"type":"modelLoad","previousComponent":{"type":"dataAccess","previousComponent":{"type":"dataCollect","previousComponent":null,"status":"success","returnType":"origindata","params":{"url":"http://ai-sample.oss-cn-hangzhou.aliyuncs.com/image_classification/datasets/eCommerceImageClassification.zip"}},"status":"not execute","returnType":"data","params":{"imgSize":[256,256]}},"status":"not execute","returnType":"model","params":{"modelName":"test1"}},{"type":"modelTrain","previousComponent":{"type":"modelLoad","previousComponent":{"type":"dataAccess","previousComponent":{"type":"dataCollect","previousComponent":null,"status":"success","returnType":"origindata","params":{"url":"http://ai-sample.oss-cn-hangzhou.aliyuncs.com/image_classification/datasets/eCommerceImageClassification.zip"}},"status":"not execute","returnType":"data","params":{"imgSize":[256,256]}},"status":"not execute","returnType":"model","params":{"modelName":"test1"}},"status":"not execute","returnType":"modeltosave","params":{"epochs":30}},{"type":"modelEvaluate","previousComponent":{"type":"modelTrain","previousComponent":{"type":"modelLoad","previousComponent":{"type":"dataAccess","previousComponent":{"type":"dataCollect","previousComponent":null,"status":"success","returnType":"origindata","params":{"url":"http://ai-sample.oss-cn-hangzhou.aliyuncs.com/image_classification/datasets/eCommerceImageClassification.zip"}},"status":"not execute","returnType":"data","params":{"imgSize":[256,256]}},"status":"not execute","returnType":"model","params":{"modelName":"test1"}},"status":"not execute","returnType":"modeltosave","params":{"epochs":30}},"status":"not execute","returnType":"evaluate"}],"currentIndex":1,"error":"Error: ENOENT: no such file or directory, open '/Users/yangxiayan/Documents/duoduo/pipcook-example/pipcook-project/.pipcook-log/datasets/eCommerceImageClassification/images/035_810.jpg'","startTime":1577610335586,"endTime":1577610508136,"predictServer":true,"onlyPredict":false,"status":"error"}

**Comment by utkobe** [comment]
你好，这个问题是之前对 data access 的改动导致收集和接入插件不兼容导致的，已在最新的代码中修复

**Comment by anyexinglu** [comment]
> 你好，这个问题是之前对 data access 的改动导致收集和接入插件不兼容导致的，已在最新的代码中修复

OKOK，请问怎么使用最新，重装 @pipcook/pipcook-cli 还是重新init初始化？

**Comment by utkobe** [comment]
@anyexinglu  不需要重装和重新初始化的，直接在有 package.json 的目录执行 npm install 来更新包就好

**Comment by anyexinglu** [comment]
> @anyexinglu 不需要重装和重新初始化的，直接在有 package.json 的目录执行 npm install 来更新包就好

这样是OK，但又有新的问题了：

![image](https://user-images.githubusercontent.com/8243326/71569036-0cef5b80-2b07-11ea-8cb7-accd7b336307.png)

**Comment by utkobe** [comment]
@anyexinglu  可能是由于国内访问谷歌云服务有问题，我把模型迁移到阿里云了, 再重新更新一下试试？
如果还是有问题，可以尝试直接打开一下报错的那个请求地址，看看是不是开了一些网络代理影响了网络请求

**Comment by anyexinglu** [comment]
谢谢，现在像是跑通了

![image](https://user-images.githubusercontent.com/8243326/71609071-8dbe5e00-2bc0-11ea-8c1a-0c64d154b10b.png)

在努力意会，跑出来的结果是啥意思。。。

![image](https://user-images.githubusercontent.com/8243326/71609084-a75fa580-2bc0-11ea-8a63-d65884e45e13.png)

**Comment by anyexinglu** [comment]
能跑通，那这个issue我close了啊

Happy new year 😊
