### ISSUE TITLE
The migration script should be tested.

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#419]
The scheme could be:
1. Prepare some old version databases on OSS.
2. Create some jobs respectively from each version to migrate.
3. Test the basic operations to the migrated databases.

**Comment by FeelyChau** [comment]
But I have no idea about testing the down script by the CI job.

**Comment by yorkie** [comment]
Just figure out an easy way to test the migration scripts is to save the databases with version, and do bootstrap with some of them.

**Comment by FeelyChau** [comment]
The migration script is not necessary for Pipcook v2.
This issue could be closed.
