### ISSUE TITLE
Build: Faster Building Process

### ISSUE THREAD

**Issue by WenheLI** [alibaba/pipcook#432]
I am currently experimenting with some SOTA ts compiler and try to find one that could decrease the building time greatly. 

Below is a table for the benchmark (does not include plugins & pipboard):

| Compiler | Exec Time |
-----------|------------|
| tsc  |  11.6s |
| esbuild | 1.4s |
| esbuild in parallel | 1.0s |
| swc | 1.2s (Does not support decorator) |

However, with the great building speed, we make a compromise on type-checking.

**Comment by yorkie** [comment]
Obviously esbuild in parallel wins!
