### ISSUE TITLE
Actions speed up.

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#437]
This is an actions speed-up scheme.
Using [Artifact](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts) and [Cache](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) to make actions high-efficiency.

![image](https://user-images.githubusercontent.com/10196611/89995942-c5e06000-dcbc-11ea-87a3-f99c545595dc.png)

**Comment by yorkie** [comment]
What files will be put to artifact?

**Comment by FeelyChau** [comment]
For npm project, [it should be all the workspace](https://github.com/actions/upload-artifact#uploading-to-the-same-artifact).

**Comment by yorkie** [comment]
I think the lint should be in front of the npm-install.

**Comment by FeelyChau** [comment]
> I think the lint should be in front of the npm-install.

Without npm-install, the lint tools will not be installed.

**Comment by FeelyChau** [comment]
CI speed is not a problem anymore.
This issue could be closed.
