### ISSUE TITLE
Bug fix: 1.1.1

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#456]
There are some bugs in 1.1.0, we need to fix them ASAP:
1. migration script error. #450 #440 
2. pipcook-plugin-tensorflow-image-classification-evaluator [type error](https://github.com/imgcook/pipcook-plugin-tensorflow-image-classification-evaluator/pull/1). 
3. pipcook-plugin-detectron-model-train [empty dict error](https://github.com/imgcook/pipcook-plugin-detectron-model-train/pull/1)
4. Memory leak when run pipeline from `./example/pipelines/databinding-image-classification.json` @rickycao-qy 
5. Command option `--tuna` missing #453 
6. generate output after job status updated #454

**Comment by yorkie** [comment]
Does these get fixed?

**Comment by FeelyChau** [comment]
Done and bump version 1.1.1 #463 #464 .
