### ISSUE TITLE
meta: Would it add benchmark and more standardized unit test?

### ISSUE THREAD

**Issue by Txiaozhe** [alibaba/pipcook#47]

**Comment by yorkie** [comment]
See https://github.com/alibaba/pipcook/blob/master/packages/pipcook-core/src/utils/logger_test.ts, you could write more like this :)

**Comment by Txiaozhe** [comment]
oo
and do benchmark?

**Comment by yorkie** [comment]
> oo
> and do benchmark?

Nope, we don't have any plan for benchmarks.

**Comment by Txiaozhe** [comment]
> > oo
> > and do benchmark?
> 
> Nope, we don't have any plan for benchmarks.

oo
