### ISSUE TITLE
costa: make the package boa, core to be a part of plugin-runtime

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#475]
At this time, the package `boa` is a plugin dependency (if  needed), if the plugins in one pipeline depend on more than one version of boa, there will be some problems:
1. costa only support one boa object actually.
2. need to download more than one version of boa (it's too slow).

If boa is a part of the plugin-runtime, we will get:

1. faster installation
2. clearer runtime definition
3. more explicit dependencies

User still cloud install 2 or more versions of boa, but they should be completely isolated between the these nodejs projects.
Plugin package could be:
```json
{
  "name": "plugins-data-process",
  "version": "1.0.0",
  "pipcook": {
    "category": "dataProcess",
    "datatype": "image",
    "runtimeVersion": "^1.0.0"
  },
  "conda": {
    "tensorflow": "2.2.0"
  }
}
```
use `runtimeVersion` to declare the runtime version.

**Comment by yorkie** [comment]
I'm -1 on this style of an issue for:

- the title is too long
- don't document the thoughts only, please describe the steps
- write a problem that you want to resolve

**Comment by FeelyChau** [comment]
> I'm -1 on this style of an issue for:
> 
> * the title is too long
> * don't document the thoughts only, please describe the steps
> * write a problem that you want to resolve

Not finished yet, mistakenly pressed enter...

**Comment by yorkie** [comment]
The most important problem is the inconsistency, we have to put the boa dist to node_modules.

**Comment by FeelyChau** [comment]
> The most important problem is the inconsistency, we have to put the boa dist to node_modules.

We can import the boa in the plugin entry, and set it to the global.

**Comment by yorkie** [comment]
@FeelyChau Thanks for this investigation, it's really great job that you started. But as you mentioned before, we have to maintain multiple versions for boa, and it looks weird for some of Node.js players which mean we added additional APIs without loading them, that's out of thinking for developers just like me :)

IMO the correct way about this issue should be to keep the same UX(user experience) to Node.js and decrease the installation cost silently. 

BTW before starting some of the improvement works, we need to visualize the bootstrap stages and their costs, then we can make a better decision based on that.

**Comment by FeelyChau** [comment]
1. Considering the what you said, we could pass the runtime into plugin by function parameter.
2. This pattern is used in the NodeJS ecosystem, even in `Pipcook`: the test framework `jasmine`.
3. `visualize the bootstrap stages and their costs` +1.

**Comment by yorkie** [comment]
What I did mean is that we should keep boa and core to be dependencies in `package.json`, which is the only way to use additional packages for Node.js developers.

**Comment by FeelyChau** [comment]
> What I did mean is that we should keep boa and core to be dependencies in `package.json`, which is the only way to use additional packages for Node.js developers.

Of course, we could define the dependence in `devDependencies`.

**Comment by yorkie** [comment]
Why? boa and core are used in runtime, so I think they must be in `dependencies`.

**Comment by FeelyChau** [comment]
> Why? boa and core are used in runtime, so I think they must be in `dependencies`.

OK, if that, we should implement the plugin package manager first.

**Comment by FeelyChau** [comment]
We could get the job status though defining the job-status-protocol on `runtime`.

**Comment by FeelyChau** [comment]
In Pipcook v2, `boa` has been moved into the [`framework`](https://github.com/alibaba/pipcook/blob/main/docs/manual/intro-to-framework.md).
