### ISSUE TITLE
sdk: add a fallback function to write custom `onerror` handler

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#503]
ng-pipboard added a new page https://pipboard.vercel.app/index.html#/connect, which will be redirected when occurring network errors. Now I implemented this logic manually in every call to SDK, that's great if we can just add an error handler when [creating the client](https://github.com/imgcook/pipboard/blob/master/src/utils/common.js):

```js
const pipcook = new PipcookClient(host, port, {
  onerror: (err) => { ... }
});

// or using EventEmitter
pipcook.on('error', (err) => { ... });
```

**Comment by FeelyChau** [comment]
There is no `SDK` anymore in V2, this issue should be closed now.
