### ISSUE TITLE
init: failed to initialize Pipcook with the error Error: Command failed: "npm" init -f

### ISSUE THREAD

**Issue by jan-www** [alibaba/pipcook#505]
Cannot init pipcook in windows platform

![image](https://user-images.githubusercontent.com/23256614/91122765-b81fd700-e6cd-11ea-9ea2-3570335f824f.png)

**Comment by yorkie** [comment]
@FeelyChau See https://github.com/alibaba/pipcook/blob/master/packages/cli/src/actions/init.ts#L18, I guess the Windows don't support wrapping a command with quotes.

**Comment by FeelyChau** [comment]
We need windows device to test current case, and I think there is a lot of work to be done to support windows, eg:
shell command dependencies(tar, curl, md5, sh).
boa build-chain confirm.

**Comment by yorkie** [comment]
But I think we can do start from this issue.

**Comment by lililbwl** [comment]
so,is there a way to solve the "Error:Command failed:'npm' init if"?

**Comment by FeelyChau** [comment]
> so,is there a way to solve the "Error:Command failed:'npm' init if" on windows device ?

Hi @lililbwl , Pipcook v2.1.3 is ready for windows, would you try it again?

**Comment by FeelyChau** [comment]
I think this issue is done. see #842 for more details.
