### ISSUE TITLE
cli: confusing work directory of docker image

### ISSUE THREAD

**Issue by liangzr** [alibaba/pipcook#506]
The Dockerfile's `WORKDIR` is set to `/opt/pipcook` now, however, the default user named `defaults` have no permission access this directory once we start a container, and failed to save the output of `pipcook run` executed immediately. 

How about setting `WORKDIR` to the user home directory, or any suggestion?

![image](https://user-images.githubusercontent.com/3992942/91127816-9f1d2300-e6d9-11ea-9c9b-2fbb5746019e.png)

**Comment by yorkie** [comment]
Does `WORKDIR $HOME` work for you?

**Comment by liangzr** [comment]
> Does `WORKDIR $HOME` work for you?

Seems `$HOME` isn't work in `WORKDIR` statement, see https://docs.docker.com/engine/reference/builder/#workdir

**Comment by yorkie** [comment]
It works for me as:

```sh
$ docker run -it fc4ec3cb9b7b /bin/bash
bash-4.2$ pwd
/opt/app-root/src
bash-4.2$ echo $HOME
/opt/app-root/src
```

**Comment by liangzr** [comment]
Gotcha! `$HOME` has been set in Dockerfile explicitly at previous layers :P

So we do use `WORKDIR $HOME` instead?

**Comment by yorkie** [comment]
> Gotcha! `$HOME` has been set in Dockerfile explicitly at previous layers :P
> 
> So we do use `WORKDIR $HOME` instead?

I agree, and may I ask you a PR for that?

**Comment by liangzr** [comment]
@yorkie I have started a PR above :)
