### ISSUE TITLE
cnpm install does not work for new cloned-packages

### ISSUE THREAD

**Issue by WenheLI** [alibaba/pipcook#541]
I encountered the following errors, when I tried to operate `cnpm install` for new cloned packages:

```
> @pipcook/boa@1.1.2 compile /Users/ericli/Desktop/dev/new/pipcook/packages/boa
> node-gyp configure && node-gyp build

/Users/ericli/Desktop/dev/new/pipcook/node_modules/_node-gyp@5.1.1@node-gyp/bin/node-gyp.js
/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: line 7: /Users/ericli/Desktop/dev/new/pipcook/node_modules/_node-gyp@5.1.1@node-gyp/bin/node-gyp.js: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @pipcook/boa@1.1.2 compile: `node-gyp configure && node-gyp build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @pipcook/boa@1.1.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

And this error will magically get fixed when I run the `cnpm install` a second time.

**Comment by yorkie** [comment]
I reproduced this issue on my macbook, and found the dir "_node-gyp@5.1.1@node-gyp" doesn't exist, but "node-gyp" does.

**Comment by WenheLI** [comment]
Turns out to be a mismatch of `npm` and `cnpm`. This could be fixed after `yarn` is launched.
#543

**Comment by yorkie** [comment]
@WenheLI Oops, does it mean npm is deprecated after #543?

**Comment by WenheLI** [comment]
> @WenheLI Oops, does it mean npm is deprecated after #543?

If we can find a way to determine which cli (yarn or npm) user is using, we can still keep `npm` as an option.
This bug is essentially introduced by lerna as lerna uses a different package management tool if we do not explicitly name it.

**Comment by yorkie** [comment]
Oh, let's deprecate the lerna dependent ASAP :(

**Comment by FeelyChau** [comment]
This issue should be closed because we reduced the packages, and `lerna` works fine now.
