### ISSUE TITLE
daemon: test cases for services

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#564]
The coverage of `daemon` is ~50% now, we should improve it.
![image](https://user-images.githubusercontent.com/10196611/92440744-8c2d4700-f1df-11ea-9222-541a194091d1.png)
![image](https://user-images.githubusercontent.com/10196611/92440993-fa720980-f1df-11ea-9b75-a9bcd67e9c60.png)
![image](https://user-images.githubusercontent.com/10196611/92441023-078ef880-f1e0-11ea-95e6-859c920c8212.png)

Here is my plan：

- [x]  controller test case

There have been a number of test cases, but not enough. I'll add cases for every api before 09/17.

- - [x] `Job`, `Pipeline` #575 

- - [x] `App`,  `Plugin`, `Log`, `Playground`, `Base` #577 

- [ ] service test case

There are only a handful of cases for now. It will be done before 09/30.

I expect the coverage will raise to 75% when v1.3.0 released.

**Comment by yorkie** [comment]
Is there any coverage table to show which parts are able to be improved?

**Comment by FeelyChau** [comment]
> Is there any coverage table to show which parts are able to be improved?

Uploaded the coverage detail.

**Comment by FeelyChau** [comment]
All test cases have been added, closed now.
