### ISSUE TITLE
To provide faster object-detection models, such as SSD and YOLO

### ISSUE THREAD

**Issue by rickycao-qy** [alibaba/pipcook#568]
According to the investigations about our users, the object-detection pipeline is heavily used. One of the reasons is that web developers need to recognize components, modules, elements in the web page. Both the type and location of components are of interest.

However, One of problem now is that we only provide support for Faster RCNN and mask RCNN. These models are quite accurate but slow compared with some other models. 

Meanwhile, data with component recognition are quite simple, without too much information, especially when these samples are synthetic data.

To provide a faster pipeline, it's good to have a smaller and fast model, such as YOLO and SSD

The data-collect, data-access plugins can be reused in this case.

**Comment by FeelyChau** [comment]
Yolo is available in v2. see: https://github.com/alibaba/pipcook/blob/main/example/pipelines/object-detection-yolo.json
