### ISSUE TITLE
Stream-based Pipeline & Plugins

### ISSUE THREAD

**Issue by WenheLI** [alibaba/pipcook#571]
We have implemented a steam-based pipeline for tensorflow-image classification, and we got a huge performance boost in terms of execution time (see #410 )

We should also modify the rest of plugins here:

- [ ] [pipcook-plugin-tensorflow-bert-ner-model-train](https://github.com/imgcook/pipcook-plugin-tensorflow-bert-ner-model-train)
<del>
- [ ] [pipcook-plugin-tensorflow-image-generation-model-train](https://github.com/imgcook/pipcook-plugin-tensorflow-image-generation-model-train) (use batch) 
</del>

**Comment by ZijinGao** [comment]
Hi! I'm interested in contributing to the pipcook-plugin-tensorflow-bert-ner-model-train plugin. Would like to know it in details.

**Comment by FeelyChau** [comment]
In v2, all the scripts are stream-based. This issue is not applicable anymore. Closed.
