### ISSUE TITLE
Daemon should handle npm packages from different sources

### ISSUE THREAD

**Issue by rickycao-qy** [alibaba/pipcook#579]
We are supporting four different sources of npm packages now: npm registry / git address / url download / local upload.

The problem is that we mix up these different sources and cannot distinguish between them after installed. Pipcook now will only record the package name. So if you want to fetch information about this package, you will by default fetch it from npm registry and it probably does not exist in npm at all.

We need to change the way that when the source is git/url/upload, we save the package, fetch the package info, compare md5 with former packages and install them accordingly. Meanwhile, we need to record the original source.

![image](https://user-images.githubusercontent.com/31037093/93282172-594b0a80-f800-11ea-8387-21b6d4fb453f.png)

**Comment by FeelyChau** [comment]
Daemon has been removed in v2, this issue should be closed now.
