### ISSUE TITLE
deamon: support config daemon is only serving at localhost

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#599]
It allows user to config the daemon serving host, for example, 127.0.0.1, to avoid the remote access.

**Comment by yorkie** [comment]
1. save this config in daemon.json?
2. `pipcook daemon start --host 127.0.0.1`?

**Comment by FeelyChau** [comment]
> 1. save this config in daemon.json?
> 2. `pipcook daemon start --host 127.0.0.1`?

I think the port should be configurable too.

**Comment by FeelyChau** [comment]
If we use `pipcook daemon start --host 127.0.0.1` to set the host, what does the restart behave?

**Comment by yorkie** [comment]
Restart should keep the last configuration IMO.

**Comment by FeelyChau** [comment]
> Restart should keep the last configuration IMO.

So we should overwrite the config file.

**Comment by yorkie** [comment]
What about `pipcook daemon start` after reboot the machine?

**Comment by FeelyChau** [comment]
Pipcook v2 is available, and we do not have the daemon processor anymore, this issue should be closed.
