### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:6927

### ISSUE THREAD

**Issue by a896853205** [alibaba/pipcook#613]
系统版本: Microsoft Windows [版本 10.0.18362.1082]
使用`npm install -g @pipcook/pipcook-cli`安装的pipcook
`pipcook --help`可以出现正常菜单
pipeline.json
```
{
  "plugins": {
    "dataCollect": {
      "package": "@pipcook/plugins-mnist-data-collect",
      "params": {
        "trainCount": 8000,
        "testCount": 2000
      }
    },
    "dataAccess": {
      "package": "@pipcook/plugins-pascalvoc-data-access"
    },
    "dataProcess": {
      "package": "@pipcook/plugins-image-data-process",
      "params": {
        "resize": [28,28]
      }
    },
    "modelDefine": {
      "package": "@pipcook/plugins-tfjs-simplecnn-model-define"
    },
    "modelTrain": {
      "package": "@pipcook/plugins-image-classification-tfjs-model-train",
      "params": {
        "epochs": 15
      }
    },
    "modelEvaluate": {
      "package": "@pipcook/plugins-image-classification-tfjs-model-evaluate"
    }
  }
}
```
使用脚本`pipcook run pipeline.json`时终端显示
`connect ECONNREFUSED 127.0.0.1:6927`

**Comment by yorkie** [comment]
可以按照这个文档初始化一下环境 https://alibaba.github.io/pipcook/#/zh-cn/manual/pipcook-tools?id=%e7%8e%af%e5%a2%83%e8%ae%be%e7%bd%ae

**Comment by AnselDai** [comment]
I meet the same problem on Mac. I am using docker to run pipcook
The Dockerfile is copied from https://github.com/alibaba/pipcook/blob/main/docker/Dockerfile
The Demo I ran is https://alibaba.github.io/pipcook/#/zh-cn/tutorials/component-object-detection
How can I solve that problem?

**Comment by FeelyChau** [comment]
> I meet the same problem on Mac. I am using docker to run pipcook
> The Dockerfile is copied from https://github.com/alibaba/pipcook/blob/main/docker/Dockerfile
> The Demo I ran is https://alibaba.github.io/pipcook/#/zh-cn/tutorials/component-object-detection
> How can I solve that problem?

Deamon should be started manually before running the pipeline:
```sh
$ pipcook daemon start
```
