### ISSUE TITLE
pipcook init

### ISSUE THREAD

**Issue by wangjpLancelote** [alibaba/pipcook#624]
初始化的过程中
npm install @pipcook/boa的过程中
均提示numpy==1.17.4版本报错

ERROR: Could not find a version that satisfies the requirement numpy==1.17.4 (from -r /Users/wangjianping/pipcook/node_modules/@pipcook/boa/requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for numpy==1.17.4 (from -r /Users/wangjianping/pipcook/node_modules/@pipcook/boa/requirements.txt (line 1))

**Comment by WenheLI** [comment]
@wangjpLancelote - 看起来像是网络问题 直接运行
```bash
pip install numpy==1.17.4
```
可以执行么？

**Comment by wangjpLancelote** [comment]
> @wangjpLancelote - 看起来像是网络问题 直接运行
> 
> ```shell
> pip install numpy==1.17.4
> ```
> 
> 可以执行么？

应该是网络问题，下安装包才行，pip3 install numpy 也会报错

**Comment by yorkie** [comment]
@wangjpLancelote 可以加上 BOA_TUNA=1 的环境变量。

**Comment by FeelyChau** [comment]
Pipcook 2.0 已经可用，安装时不会依赖 boa，可以用 2.0 试一试，这个 issue 暂时关闭了。仍然有问题可以重新开启。
