### ISSUE TITLE
daemon: upgrade sequelize to support JSON.

### ISSUE THREAD

**Issue by FeelyChau** [alibaba/pipcook#628]
The latest version of sequelize has supported the data type JSON, see https://sequelize.org/master/manual/other-data-types.html, it's helpful to store the pipeline parameters.

**Comment by WenheLI** [comment]
Will open another PR to use JSON type.

**Comment by yorkie** [comment]
Should this be supported at #636? @WenheLI

**Comment by FeelyChau** [comment]
> Should this be supported at #636? @WenheLI

Not yet, we need to refactor all the `params` fields to json object from string.

**Comment by FeelyChau** [comment]
Pipcook v2 is available now and it does not use `sequelize` anymore. This issue should be closed.
