### ISSUE TITLE
pipcook init failure on Ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by OMaiZaregoto** [alibaba/pipcook#632]
用VMWare在Ubuntu 18上初始化pipcook失败，不知道啥原因。原来在Win10上失败，看了之前的issue(#505 )说有可能是Windows的问题，就换成Ubuntu试试，但还是不行……故提供相关信息以反馈：
- OS：Ubuntu 18.04.1 LTS
- nodejs：14.15.0
- npm：6.14.8，没有配置cnpm
- 运行用户：非root，已使用sudo。
- 安装pipcook命令：
`npm install -g @pipcook/pipcook-cli`
- 在任意目录创建了一个目录，然后进入
`mkdir pipcook-example && cd pipcook-example`
- 在目录内执行初始化命令：
`pipcook init`

完整报错信息如下：
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

> @pipcook/boa@1.2.0 preinstall /home/mowj/.pipcook/server/node_modules/@pipcook/boa
> node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js

/bin/rm
/home/mowj/.pipcook/server/node_modules/@pipcook/boa/tools/check-dependence.js:23
    throw new TypeError(`command ${cmd} check failed: ${err}`);
    ^

TypeError: command make check failed: Error: Command failed: command -v make
    at /home/mowj/.pipcook/server/node_modules/@pipcook/boa/tools/check-dependence.js:23:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/mowj/.pipcook/server/node_modules/@pipcook/boa/tools/check-dependence.js:19:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pipcook/boa@1.2.0 preinstall: `node tools/check-dependence.js && make -C ./pybind11/ && node tools/install-python.js && node tools/install-requirements.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pipcook/boa@1.2.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mowj/.npm/_logs/2020-11-11T07_56_57_742Z-debug.log
✖ failed to initialize Pipcook with the error Error: Command failed: "npm" install @pipcook/daemon -E --production
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at /usr/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:44:25
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:23:12)
    at npmInstall (/usr/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:41:12)
    at /usr/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:160:15
    at Generator.next (<anonymous>)

**Comment by FeelyChau** [comment]
看错误信息应该是没有安装 make。

**Comment by FeelyChau** [comment]
先安装 make:
```sh
$ sudo apt-get install build-essential
```
再试一下看看。

**Comment by OMaiZaregoto** [comment]
> 先安装 make:
> 
> ```shell
> $ sudo apt-get install build-essential
> ```
> 
> 再试一下看看。

好的好的，谢谢。我再试试~

**Comment by OMaiZaregoto** [comment]
已经解决，谢谢！ @FeelyChau

**Comment by Daniel6Lee** [comment]
您好，想问一下是怎么解决的，谢谢！

**Comment by FeelyChau** [comment]
> 已经解决，谢谢！ @FeelyChau

如果错误信息一致的话，需要安装 build-essential, 否则可以单独提一个 issue。
