### ISSUE TITLE
 job is failed: costa runtime is destroyed(SIGKILL)

### ISSUE THREAD

**Issue by OMaiZaregoto** [alibaba/pipcook#635]
请问一下，我在试着运行示例后，VM的终端报了这个错：
`$ pipcook run https://raw.githubusercontent.com/alibaba/pipcook/master/example/pipelines/text-bayes-classification.json`

第一次使用pipcook，但是检查了下VM的资源，内存使用已经将近100%，不知道是否是因为内存不够，才导致运行失败的。

截图如下：
![image](https://user-images.githubusercontent.com/13087564/98796280-2c088a80-2446-11eb-84f1-e1a550a0aba3.png)

**Comment by FeelyChau** [comment]
看截图的话，可用内存只有 100MB，内存扩展到 2GB，应该可以解决。

**Comment by OMaiZaregoto** [comment]
> 看截图的话，可用内存只有 100MB，内存扩展到 2GB，应该可以解决。

谢谢，我再去试试。

**Comment by OMaiZaregoto** [comment]
可以了，我扩展到4GB了，谢谢！ @FeelyChau 
![image](https://user-images.githubusercontent.com/13087564/98801262-8c9ac600-244c-11eb-8d70-0668ddc09835.png)
