### ISSUE TITLE
torch-1.6 start download veryslow

### ISSUE THREAD

**Issue by upupzealot** [alibaba/pipcook#670]
When I'm installing plugin @pipcook/plugins-detectron-model-evaluate
The cli window says:
![image](https://user-images.githubusercontent.com/2574689/102095163-298ebb80-3e5e-11eb-9eae-c5e75c341cb1.png)
and debug window:
![image](https://user-images.githubusercontent.com/2574689/102095205-36abaa80-3e5e-11eb-8e7e-27f4d388927c.png)
but after a few minutes (3~4 mins) it says start downloading, not sure if it's normal to have such long time to wait
![image](https://user-images.githubusercontent.com/2574689/102095334-6195fe80-3e5e-11eb-82cc-0f8e8cd46ef2.png)

**Comment by FeelyChau** [comment]
@upupzealot  Pipcook 2.0 is released, it's much faster than v1.x, and it does not download the framework by pip anymore.
You could install it through:
```sh
npm uninstall @pipcook/pipcook-cli -g && npm install @pipcook/cli -g
```
And train the model:
```sh
$ pipcook train https://cdn.jsdelivr.net/gh/alibaba/pipcook@main/example/pipelines/object-detection-yolo.json -o my-pipcook
```

**Comment by FeelyChau** [comment]
This problem no longer exists in v2.0. Let's close it.
