### ISSUE TITLE
docs: document text error correction

### ISSUE THREAD

**Issue by mowatermelon** [alibaba/pipcook#678]
## 问题描述

pipcook 文档中的存在错别字

## 完整描述

- 错误文字页面 https://alibaba.github.io/pipcook/#/zh-cn/INSTALL
- 错误文字所在章节  `疑难排查`
- 错误文字完整内容

```text
### 疑难排查
如果你有任何安装方面的问题，清反馈到我们的 [issue tracker](https://github.com/alibaba/pipcook/issues/new)。
```

- 错误文字  `清` 
- 正确文字 `请`
- 页面截图

![image](https://user-images.githubusercontent.com/18508817/102986075-288b1780-454b-11eb-95ce-bf79487186b4.png)

- 涉及文档地址 
<https://github.com/alibaba/pipcook/blob/main/docs/zh-cn/INSTALL.md>

---

**Comment by yorkie** [comment]
多谢 @mowatermelon 可以帮忙提一个 PR 帮我们修改吗？

**Comment by mowatermelon** [comment]
> 多谢 @mowatermelon 可以帮忙提一个 PR 帮我们修改吗？

@yorkie  嗯嗯  PR  已经提了  <https://github.com/alibaba/pipcook/pull/679>

![image](https://user-images.githubusercontent.com/18508817/102987253-05f9fe00-454d-11eb-95ac-aed775872279.png)

**Comment by mowatermelon** [comment]
> 多谢，这里要签下我们的贡献者协议哈：https://cla-assistant.io/alibaba/pipcook?pullRequest=679

已授权~
