### ISSUE TITLE
pipcook init Error on Windows

### ISSUE THREAD

**Issue by SleepDevil** [alibaba/pipcook#699]
Have this bug been solved? #505 
I've met the same problem today.
![Snipaste_2021-01-22_11-37-31](https://user-images.githubusercontent.com/55879038/105443408-90e22b80-5ca6-11eb-9d46-4f896244cfb9.png)
Or I have to switch to Linux?

**Comment by yorkie** [comment]
Yea, Linux or macOS is required for now :(
