### ISSUE TITLE
cli: unit tests for cli

### ISSUE THREAD

**Issue by WenheLI** [alibaba/pipcook#735]
This issue is to track the unimplemented unit tests for cli.

**Comment by ZijinGao** [comment]
🙋

**Comment by WenheLI** [comment]
@ZijinGao - A good starting point for this issue could be listing the missing unit tests within the cli folder.

**Comment by FeelyChau** [comment]
> @ZijinGao - A good starting point for this issue could be listing the missing unit tests within the cli folder.

You can execute command as follows to get the coverage report:
```sh
$ yarn cov && yarn cov:report
$ open ./packages/cli/coverage/lcov-report/index.html
```

**Comment by FeelyChau** [comment]
The unit tests for cli is almost done, this issue should be closed.
