### ISSUE TITLE
I can not init this project ! Please help to have a look~~~

### ISSUE THREAD

**Issue by yanzilingyan** [alibaba/pipcook#737]
I'm use mac 64bit system. 
node v15.12.0
npm 7.6.3

`➜  demo_model1  pipcook init

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp@1.x: the non-scoped 'node-pre-gyp' package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /Users/xiaoenai/.pipcook/server/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.12.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xiaoenai/.pipcook/server/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/xiaoenai/Library/Caches/node-gyp/15.12.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/xiaoenai/Library/Caches/node-gyp/15.12.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/xiaoenai/Library/Caches/node-gyp/15.12.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/xiaoenai/.pipcook/server/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 18.7.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/15.12.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/xiaoenai/.pipcook/server/node_modules/sqlite3
npm ERR! gyp ERR! node -v v15.12.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiaoenai/.npm/_logs/2021-03-27T07_48_45_966Z-debug.log
✖ failed to initialize Pipcook with the error Error: Command failed: "npm" install @pipcook/daemon -E --production
    at checkExecSyncError (node:child_process:690:11)
    at Object.execSync (node:child_process:727:15)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:27:25
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:4:12)
    at npmInstall (/usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:24:12)
    at /usr/local/lib/node_modules/@pipcook/pipcook-cli/dist/actions/init.js:152:15
    at Generator.next (<anonymous>)
`

**Comment by yorkie** [comment]
@yanzilingyan It seems a bug from node-pre-gyp, a quick fix is downgrade the node to v14, see https://github.com/nodejs/node-gyp/issues/508#issuecomment-802998803 for details :)

**Comment by yanzilingyan** [comment]
It's normal. Thank you
