### ISSUE TITLE
mac 系统  pipcook run image-classification.json --tuna 失败  plugin install failed: null

### ISSUE THREAD

**Issue by ShanaMaid** [alibaba/pipcook#752]
> pipcook run image-classification.json --tuna

✔ plugin @pipcook/plugins-image-classification-data-collect@1.1.0 has already been installed
✔ plugin @pipcook/plugins-pascalvoc-data-access@1.1.0 has already been installed
✔ install successfully
✔ install @pipcook/plugins-tensorflow-image-classification-process@1.1.4 successfully
⚠ NODE: npm WARN plugins@1.0.0 No description
⚠ NODE: npm WARN plugins@1.0.0 No repository field.
⚠ NODE:
ℹ PYTHON: Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ℹ PYTHON: Collecting tensorflow==2.2.0
ℹ NODE: + @pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1
ℹ NODE: added 2 packages and audited 150 packages in 2.912s
ℹ NODE:
ℹ NODE: 3 packages are looking for funding
ℹ NODE:   run `npm fund` for details
ℹ NODE:
ℹ NODE: found 3 moderate severity vulnerabilities
ℹ NODE:   run `npm audit fix` to fix them, or `npm audit` for details
ℹ PYTHON:   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/49/b7/b6de9de9f14b940ad877fb376c6e1f72d6ea924affce04656b0423725e47/tensorflow-2.2.0-cp37-cp37m-macosx_10_11_x86_64.whl (175.3MB)
⚠ PYTHON: Exception:
⚠ PYTHON: Traceback (most recent call last):
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 360, in _error_catcher
⚠ PYTHON:     yield
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 442, in read
⚠ PYTHON:     data = self._fp.read(amt)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
⚠ PYTHON:     data = self.__fp.read(amt)
⚠ PYTHON:   File "/Users/mac/.pipcook/server/node_modules/@pipcook/boa/.miniconda/lib/python3.7/http/client.py", line 457, in read
⚠ PYTHON:     n = self.readinto(b)
⚠ PYTHON:   File "/Users/mac/.pipcook/server/node_modules/@pipcook/boa/.miniconda/lib/python3.7/http/client.py", line 501, in readinto
⚠ PYTHON:     n = self.fp.readinto(b)
⚠ PYTHON:   File "/Users/mac/.pipcook/server/node_modules/@pipcook/boa/.miniconda/lib/python3.7/socket.py", line 589, in readinto
⚠ PYTHON:     return self._sock.recv_into(b)
⚠ PYTHON:   File "/Users/mac/.pipcook/server/node_modules/@pipcook/boa/.miniconda/lib/python3.7/ssl.py", line 1071, in recv_into
⚠ PYTHON:     return self.read(nbytes, buffer)
⚠ PYTHON:   File "/Users/mac/.pipcook/server/node_modules/@pipcook/boa/.miniconda/lib/python3.7/ssl.py", line 929, in read
⚠ PYTHON:     return self._sslobj.read(len, buffer)
⚠ PYTHON: socket.timeout: The read operation timed out
⚠ PYTHON:
⚠ PYTHON: During handling of the above exception, another exception occurred:
⚠ PYTHON:
⚠ PYTHON: Traceback (most recent call last):
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
⚠ PYTHON:     status = self.run(options, args)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
⚠ PYTHON:     resolver.resolve(requirement_set)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
⚠ PYTHON:     self._resolve_one(requirement_set, req)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
⚠ PYTHON:     abstract_dist = self._get_abstract_dist_for(req_to_install)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
⚠ PYTHON:     self.require_hashes
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 334, in prepare_linked_requirement
⚠ PYTHON:     progress_bar=self.progress_bar
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/download.py", line 878, in unpack_url
⚠ PYTHON:     progress_bar=progress_bar
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/download.py", line 702, in unpack_http_url
⚠ PYTHON:     progress_bar)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/download.py", line 946, in _download_http_url
⚠ PYTHON:     _download_url(resp, link, content_file, hashes, progress_bar)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/download.py", line 639, in _download_url
⚠ PYTHON:     hashes.check_against_chunks(downloaded_chunks)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/utils/hashes.py", line 62, in check_against_chunks
⚠ PYTHON:     for chunk in chunks:
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/download.py", line 607, in written_chunks
⚠ PYTHON:     for chunk in chunks:
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 159, in iter
⚠ PYTHON:     for x in it:
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_internal/download.py", line 596, in resp_read
⚠ PYTHON:     decode_content=False):
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 494, in stream
⚠ PYTHON:     data = self.read(amt=amt, decode_content=decode_content)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 459, in read
⚠ PYTHON:     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
⚠ PYTHON:   File "/Users/mac/.pipcook/server/node_modules/@pipcook/boa/.miniconda/lib/python3.7/contextlib.py", line 130, in __exit__
⚠ PYTHON:     self.gen.throw(type, value, traceback)
⚠ PYTHON:   File "/Users/mac/.pipcook/plugins/conda_envs/@pipcook/plugins-tensorflow-mobilenet-model-define@1.1.1/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 365, in _error_catcher
⚠ PYTHON:     raise ReadTimeoutError(self._pool, None, 'Read timed out.')
⚠ PYTHON: pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out.
⚠ PYTHON: You are using pip version 19.0.3, however version 21.0.1 is available.
⚠ PYTHON: You should consider upgrading via the 'pip install --upgrade pip' command.
✖ plugin install failed: null

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! image-cook@1.0.0 build: `pipcook run image-classification.json --tuna`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the image-cook@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2021-04-07T07_27_26_878Z-debug.log

**Comment by ShanaMaid** [comment]
{
  "plugins": {
    "dataCollect": {
      "package": "@pipcook/plugins-image-classification-data-collect",
      "params": {
        "url": "http://ai-sample.oss-cn-hangzhou.aliyuncs.com/pipcook/datasets/component-recognition-image-classification/component-recognition-classification.zip"
      }
    },
    "dataAccess": {
      "package": "@pipcook/plugins-pascalvoc-data-access"
    },
    "dataProcess": {
      "package": "@pipcook/plugins-tensorflow-image-classification-process",
      "params": {
        "resize": [224, 224]
      }
    },
    "modelDefine": {
      "package": "@pipcook/plugins-tensorflow-mobilenet-model-define",
      "params": {
        "batchSize": 8,
        "freeze": false
      }
    },
    "modelTrain": {
      "package": "@pipcook/plugins-image-classification-tensorflow-model-train",
      "params": {
        "epochs": 15
      }
    },
    "modelEvaluate": {
      "package": "@pipcook/plugins-image-classification-tensorflow-model-evaluate"
    }
  }
}
```json
{
  "plugins": {
    "dataCollect": {
      "package": "@pipcook/plugins-image-classification-data-collect",
      "params": {
        "url": "http://ai-sample.oss-cn-hangzhou.aliyuncs.com/pipcook/datasets/component-recognition-image-classification/component-recognition-classification.zip"
      }
    },
    "dataAccess": {
      "package": "@pipcook/plugins-pascalvoc-data-access"
    },
    "dataProcess": {
      "package": "@pipcook/plugins-tensorflow-image-classification-process",
      "params": {
        "resize": [224, 224]
      }
    },
    "modelDefine": {
      "package": "@pipcook/plugins-tensorflow-mobilenet-model-define",
      "params": {
        "batchSize": 8,
        "freeze": false
      }
    },
    "modelTrain": {
      "package": "@pipcook/plugins-image-classification-tensorflow-model-train",
      "params": {
        "epochs": 15
      }
    },
    "modelEvaluate": {
      "package": "@pipcook/plugins-image-classification-tensorflow-model-evaluate"
    }
  }
}
```

**Comment by FeelyChau** [comment]
Download tensorflow error. You can try this again. Pipcook 2.0 RC version has been released, we have a pipeline for tfjs mobilenet, you can try:

下载 tensorflow 时出错了，可以重新跑一下试试。另外，pipcook 2.0 rc 版本已发布，支持 tfjs mobilenet，可以试试:

```shell
$ npm uninstall @pipcook/pipcook-cli -g
$ npm install @pipcook/cli@rc -g
$ pipcook run https://raw.githubusercontent.com/alibaba/pipcook/main/example/pipelines/mobilenet.v2.json
```

**Comment by yorkie** [comment]
https://cdn.jsdelivr.net/gh/alibaba/pipcook@main/example/pipelines/mobilenet.v2.json 应该更快。

**Comment by ShanaMaid** [comment]
已解决，谢谢

**Comment by keke0327** [comment]
![image](https://user-images.githubusercontent.com/34297445/139811326-f6a55421-4d9f-46c2-bea2-e5c3ef6e2c63.png)

**Comment by keke0327** [comment]
@FeelyChau npm install @pipcook/cli@rc -g安装失败
