### ISSUE TITLE
new pipeline workspace directory name 

### ISSUE THREAD

**Issue by ZijinGao** [alibaba/pipcook#768]
Pipeline workspace dir name generated from timestamp (e.g., "20210402155756") can be improved for better readability. 
We should consider changing it so that it's readable and can keeps its uniqueness as well. 
Maybe something like 'pipcook-workspace-timestamp'.

**Comment by FeelyChau** [comment]
How about `pipcook-job-${hhmmss}`？

**Comment by ZijinGao** [comment]
pipcook-job-${hhmmss} sounds good to me!

**Comment by yorkie** [comment]
@FeelyChau May I ask you to guide @ZijinGao to improve the default name?

**Comment by FeelyChau** [comment]
@yorkie @WenheLI @rickycao-qy  What's your opinions?

**Comment by yorkie** [comment]
LGTM

**Comment by FeelyChau** [comment]
Done by #861 .
