### ISSUE TITLE
无法运行：job is failed: costa runtime is destroyed(SIGILL)

### ISSUE THREAD

**Issue by wenjingyuer** [alibaba/pipcook#778]
系统环境：
MacBook pro M1处理器
pipline配置：
{
    "plugins": {
      "dataCollect": {
        "package": "@pipcook/plugins-mnist-data-collect",
        "params": {
          "trainCount": 8000,
          "testCount": 2000
        }
      },
      "dataAccess": {
        "package": "@pipcook/plugins-pascalvoc-data-access"
      },
      "dataProcess": {
        "package": "@pipcook/plugins-tensorflow-image-classification-process",
        "params": {
          "resize": [28, 28]
        }
      },
      "modelDefine": {
        "package": "@pipcook/plugins-tfjs-simplecnn-model-define"
      },
      "modelTrain": {
        "package": "@pipcook/plugins-image-classification-tfjs-model-train",
        "params": {
          "epochs": 15
        }
      },
      "modelEvaluate": {
        "package": "@pipcook/plugins-image-classification-tfjs-model-evaluate"
      }
    }
  }

插件列表：
% pipcook plugin list                      ┌─────────┬────────────┬─────────────────────────────────────────────────────────────┬─────────┬─────────────────┬──────────┬─────────────┐
│ (index) │     id     │                            name                             │ version │    category     │ datatype │   status    │
├─────────┼────────────┼─────────────────────────────────────────────────────────────┼─────────┼─────────────────┼──────────┼─────────────┤
│    0    │ 'gxhn14o3' │            '@pipcook/plugins-mnist-data-collect'            │ '1.1.0' │  'dataCollect'  │ 'image'  │ 'installed' │
│    1    │ 'l3lbfke6' │          '@pipcook/plugins-pascalvoc-data-access'           │ '1.1.0' │  'dataAccess'   │ 'image'  │ 'installed' │
│    2    │ 'uio401yv' │       '@pipcook/plugins-tfjs-simplecnn-model-define'        │ '1.1.0' │  'modelDefine'  │ 'image'  │ 'installed' │
│    3    │ 'bamz9d4u' │  '@pipcook/plugins-image-classification-tfjs-model-train'   │ '1.1.5' │  'modelTrain'   │ 'image'  │ 'installed' │
│    4    │ 'i94u0m73' │ '@pipcook/plugins-image-classification-tfjs-model-evaluate' │ '1.1.2' │ 'modelEvaluate' │ 'image'  │ 'installed' │
│    5    │ 'y5uw0nr9' │ '@pipcook/plugins-tensorflow-image-classification-process'  │ '1.1.4' │  'dataProcess'  │ 'image'  │ 'installed' │
└─────────┴────────────┴─────────────────────────────────────────────────────────────┴─────────┴─────────────────┴──────────┴─────────────┘

插件都安装成功了，但是运行时报错

pipcook run ./pipeline-config.json --tuna
✔ plugin @pipcook/plugins-mnist-data-collect@1.1.0 has already been installed
✔ plugin @pipcook/plugins-pascalvoc-data-access@1.1.0 has already been installed
✔ plugin @pipcook/plugins-tensorflow-image-classification-process@1.1.4 has already been installed
✔ plugin @pipcook/plugins-tfjs-simplecnn-model-define@1.1.0 has already been installed
✔ plugin @pipcook/plugins-image-classification-tfjs-model-train@1.1.5 has already been installed
✔ plugin @pipcook/plugins-image-classification-tfjs-model-evaluate@1.1.2 has already been installed
ℹ start to create pipeline
✔ pipeline is created: jzr3bsjf, installing
ℹ plugin @pipcook/plugins-mnist-data-collect@1.1.0 already installed
ℹ plugin @pipcook/plugins-pascalvoc-data-access@1.1.0 already installed
ℹ plugin @pipcook/plugins-tensorflow-image-classification-process@1.1.4 already installed
ℹ plugin @pipcook/plugins-tfjs-simplecnn-model-define@1.1.0 already installed
ℹ plugin @pipcook/plugins-image-classification-tfjs-model-train@1.1.5 already installed
ℹ plugin @pipcook/plugins-image-classification-tfjs-model-evaluate@1.1.2 already installed
✔ pipeline installed successfully, start to run job
✔ job is created: 3ox2b2ym, running
ℹ [job] running
ℹ [job] running dataCollect start
ℹ start loading plugin @pipcook/plugins-mnist-data-collect
ℹ [job] fails
**✖ job is failed: costa runtime is destroyed(SIGILL).**

**Comment by FeelyChau** [comment]
需要在 m1 设备上测试下，周一才能 debug 了。

**Comment by FeelyChau** [comment]
@CHOOSE6868 可以提供下 `process.arch` 么？

**Comment by FeelyChau** [comment]
@wenjingyuer M1 暂时还无法支持，目前 pipcook v2.0 已经在跟进处理了，等 tfjs 支持 M1 就可以了。可以关注 issue #818
这个 issue 暂时先关闭了，有问题的话可以重新开启。
