### ISSUE TITLE
 job is failed: read timeout.

### ISSUE THREAD

**Issue by byteHulk** [alibaba/pipcook#792]
✔ plugin @pipcook/plugins-object-detection-pascalvoc-data-collect@1.1.0 has already been installed
✔ plugin @pipcook/plugins-coco-data-access@1.1.3 has already been installed
✔ plugin @pipcook/plugins-pytorch-yolov5-model-define@1.1.0 has already been installed
✔ plugin @pipcook/plugins-pytorch-yolov5-model-train@1.1.2 has already been installed
✔ plugin @pipcook/plugins-pytorch-yolov5-model-evaluate@1.1.0 has already been installed
ℹ start to create pipeline
✔ pipeline is created: w558gzf8, installing
ℹ plugin @pipcook/plugins-object-detection-pascalvoc-data-collect@1.1.0 already installed
ℹ plugin @pipcook/plugins-coco-data-access@1.1.3 already installed
ℹ plugin @pipcook/plugins-pytorch-yolov5-model-define@1.1.0 already installed
ℹ plugin @pipcook/plugins-pytorch-yolov5-model-train@1.1.2 already installed
ℹ plugin @pipcook/plugins-pytorch-yolov5-model-evaluate@1.1.0 already installed
✔ pipeline installed successfully, start to run job
✔ job is created: 6epqyp5y, running
ℹ [job] running
ℹ [job] running dataCollect start
ℹ start loading plugin @pipcook/plugins-object-detection-pascalvoc-data-collect
ℹ @pipcook/plugins-object-detection-pascalvoc-data-collect plugin is loaded
ℹ downloading dataset ...
ℹ unzip and collecting data...
ℹ [job] running dataCollect end
ℹ [job] running dataAccess start
ℹ start loading plugin @pipcook/plugins-coco-data-access
ℹ @pipcook/plugins-coco-data-access plugin is loaded
ℹ create a result "6naq9e1y" for plugin "@pipcook/plugins-coco-data-access@1.1.3"
ℹ [job] running dataAccess end
ℹ [job] running modelDefine start
ℹ start loading plugin @pipcook/plugins-pytorch-yolov5-model-define
ℹ [job] fails
✖ job is failed: read timeout.

**Comment by byteHulk** [comment]
pipcook % pipcook run pipeline-config.json --tuna

**Comment by yorkie** [comment]
It seems the network timeout, may I ask you to have a retry?

**Comment by FeelyChau** [comment]
> pipcook run pipeline-config.json --tuna

@byteHulk

Pipcook 2.0 is released, you can run the command as follow to train the model for object detection:

```sh
$ pipcook train https://cdn.jsdelivr.net/gh/alibaba/pipcook@main/example/pipelines/object-detection-yolo.json -o output
```

And serve the model by:

```sh
$ pipcook serve ./output
```
