### ISSUE TITLE
training failed

### ISSUE THREAD

**Issue by Elfilali-Taoufiq** [alibaba/pipcook#804]
Hello and thanks for this great work,

I'm trying to use the notebook "pipcook_object_detection.ipynb", in the moment of starting training, i had this error:

```
[start]: run pipeline from https://raw.githubusercontent.com/alibaba/pipcook/main/example/pipelines/object-detection-yolov5.json
[start]: downloading pipeline config file
[fail]: fetch config failed: Request failed with status code 404
```
then I  jumped to the repo github, and i found that the file 'Object-detection-yolov5.json' not found

**Comment by FeelyChau** [comment]
The main branch has migrated to v2.x, so the address `https://raw.githubusercontent.com/alibaba/pipcook/main/example/pipelines/object-detection-yolov5.json` should be updated to `https://raw.githubusercontent.com/alibaba/pipcook/v1.x/example/pipelines/object-detection-yolov5.json`.
May I ask you to help us to fix it?

**Comment by Elfilali-Taoufiq** [comment]
ok, thank you for the response @FeelyChau 

then I will try to fix it
