### ISSUE TITLE
pipcook run执行提示Cannot find module '@tensorflow/tfjs-node'

### ISSUE THREAD

**Issue by ywager** [alibaba/pipcook#828]
env:
ubuntu 16.0.4

pipcook --version
2.0.0

node -v
v12.19.0

json:
```
{
  "specVersion": "2.0",
  "type": "ImageClassification",
  "datasource": "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@c1da85c/scripts/image-classification/build/datasource.js?url=http://ai-sample.oss-cn-hangzhou.aliyuncs.com/image_classification/datasets/imageclass-test.zip",
  "dataflow": [
    "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@c1da85c/scripts/image-classification/build/dataflow.js?size=224&size=224"
  ],
  "model": "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@c1da85c/scripts/image-classification/build/model.js",
  "options": {
    "framework": "mobilenet@1.0.0",
    "train": {
      "epochs": 10,
      "validationRequired": true
    }
  }
}
```

输出:

ℹ preparing framework
ℹ preparing scripts
ℹ preparing artifact plugins
ℹ initializing framework packages
ℹ running data source script
Platform node has already been set. Overwriting the platform with [object Object].
downloading dataset ...
unzip and collecting data...
ℹ running data flow script
Platform node has already been set. Overwriting the platform with [object Object].
ℹ running model script
✖ run pipeline error: Error: Cannot find module '@tensorflow/tfjs-node'
Require stack:
- /root/.pipcook/script/efac80d82a565ab60fa6af8546b0cf9b
- /opt/node-v12.19.0-linux-x64/lib/node_modules/@pipcook/cli/node_modules/@pipcook/costa/dist/utils.js
- /opt/node-v12.19.0-linux-x64/lib/node_modules/@pipcook/cli/node_modules/@pipcook/costa/dist/index.js
- /opt/node-v12.19.0-linux-x64/lib/node_modules/@pipcook/cli/dist/runtime.js
- /opt/node-v12.19.0-linux-x64/lib/node_modules/@pipcook/cli/dist/bin/pipcook.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.@tensorflow/tfjs-node (/root/.pipcook/script/efac80d82a565ab60fa6af8546b0cf9b:454:18)
    at __webpack_require__ (/root/.pipcook/script/efac80d82a565ab60fa6af8546b0cf9b:555:42)
    at eval (webpack://@pipcook/mobilenet-pipeline/./dist/model.js?:61:23)
    at Object../dist/model.js (/root/.pipcook/script/efac80d82a565ab60fa6af8546b0cf9b:29:1)
    at __webpack_require__ (/root/.pipcook/script/efac80d82a565ab60fa6af8546b0cf9b:555:42)
    at /root/.pipcook/script/efac80d82a565ab60fa6af8546b0cf9b:566:37

**Comment by FeelyChau** [comment]
The script version `c1da85c` does not adapt to the currently released version, you should try:
```sh
$ npm install @pipcook/cli@beta -g
```
And run the pipeline again.

**Comment by ywager** [comment]
Thanks for such a quick answer, it has been resolved after changing to the @pipcook/cli@beta version.
