### ISSUE TITLE
pipcook run ####遇到问题

### ISSUE THREAD

**Issue by tiancaidiyibu** [alibaba/pipcook#857]
型号：m1  macbook
[01:14:17:782] ℹ preparing framework
[01:14:17:783] ✖ run pipeline error: Cannot read property 'framework' of undefined

**Comment by FeelyChau** [comment]
M1 的支持还在进行中，目前的情况是 tfjs 还不支持 M1，导致无法打包对应的 framework 包。我们正在通过手动编译 tfjs 的方式来支持，但是目前还有一些问题。
如果有进展我们会同步到这个 issue 中。

**Comment by FeelyChau** [comment]
关联 issue: https://github.com/tensorflow/tfjs/issues/4514

**Comment by tiancaidiyibu** [comment]
@FeelyChau 换了一台mac电脑(CPU Intel Core i5，系统版本11.5.2 )   运行pipcook run 还是报错
[08:45:37:769] ℹ preparing framework
[08:45:37:770] ✖ run pipeline error: Cannot read property 'framework' of undefined

**Comment by FeelyChau** [comment]
> @FeelyChau 换了一台mac电脑(CPU Intel Core i5，系统版本11.5.2 ) 运行pipcook run 还是报错
> [08:45:37:769] ℹ preparing framework
> [08:45:37:770] ✖ run pipeline error: Cannot read property 'framework' of undefined

运行的命令是什么，看起来像是没有使用正确的 pipeline 文件。

**Comment by tiancaidiyibu** [comment]
@FeelyChau 
{
  "plugins": {
    "dataCollect": {
      "package": "@pipcook/plugins-image-classification-data-collect",
      "params": {
        "url": "file:///Users/adminx/Desktop/Ikki-study/iconcook/iconData/imgs.zip"
      }
    },
    "dataAccess": {
      "package": "@pipcook/plugins-pascalvoc-data-access"
    },
    "dataProcess": {
      "package": "@pipcook/plugins-tfjs-image-classification-process",
      "params": {
        "resize": [224, 224]
      }
    },
    "modelDefine": {
      "package": "@pipcook/plugins-tfjs-mobilenet-model-define",
      "params": {
        "freeze": false
      }
    },
    "modelTrain": {
      "package": "@pipcook/plugins-image-classification-tfjs-model-train",
      "params": {
        "batchSize": 64,
        "epochs": 12
      }
    },
    "modelEvaluate": {
      "package": "@pipcook/plugins-image-classification-tfjs-model-evaluate"
    }
  }
}

**Comment by FeelyChau** [comment]
需要使用新版本的 pipeline 文件: https://github.com/alibaba/pipcook/tree/main/example/pipelines

**Comment by tiancaidiyibu** [comment]
> @tiancaidiyibu逻辑新的管道文件之后是否能正常运行？

可以正常运行了

**Comment by FeelyChau** [comment]
@tiancaidiyibu 好的，那这个 issue 关闭啦。
