### ISSUE TITLE
run pipeline error: Forbidden

### ISSUE THREAD

**Issue by rhinonan** [alibaba/pipcook#859]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

* OS: macOS 11.5.2
* nodejs: 16.9.0

```shell
sudo npm install -g @pipcook/cli

sudo pipcook train https://cdn.jsdelivr.net/gh/alibaba/pipcook@main/example/pipelines/image-classification-mobilenet.json -o output. # => run pipeline error: Forbidden

pipcook train https://cdn.jsdelivr.net/gh/alibaba/pipcook@main/example/pipelines/image-classification-mobilenet.json -o output. # => run pipeline error: Forbidden(widthout sudo)
```

just run as README.MD QUICK START

**Comment by rhinonan** [comment]
node 14 is fine

**Comment by FeelyChau** [comment]
The framework for node v16 is not ready for now, we will update the document when it's done.

**Comment by keke0327** [comment]
nodejs:14.0.0

**Comment by keke0327** [comment]
@FeelyChau node版本14.0.0也 run pipeline error: Forbidden

**Comment by FeelyChau** [comment]
> @FeelyChau node版本14.0.0也 run pipeline error: Forbidden

What's the OS version and the cpu type?

**Comment by keke0327** [comment]
OS:win10
Inter(R) Core(TM) i5-7400 CPU

**Comment by FeelyChau** [comment]
@keke0327 Please upgrade Node to v14.17.0, we only packed the framework packages for N-API v8.

**Comment by keke0327** [comment]
node版本升级到v14.17.0后
run pipeline error: EPERM: operation not permitted, rename 'C:\Users\admin\.pipcook\framework\tmp\55f4079d09d4e45a68f9d0bfe352df5b' -> 'C:\Users\admin\.pipcook\framework\55f4079d09d4e45a68f9d0bfe352df5b'

**Comment by FeelyChau** [comment]
@keke0327 需要用管理员模式运行终端，然后跑 pipcook。

**Comment by keke0327** [comment]
谢谢~
