### ISSUE TITLE
proposal to add some labels to manage our issues

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#9]
The labels list are the following:

- `pipcook-core`: the pipcook-core issues
- `build`: the build(CI/CD) issues
- `plugin`: the plugin issues
- `tests`: the test issues
- `model`: the model issues

@utkobe may I ask you to have review the above, I will do an operation after getting approvals of you.

**Comment by utkobe** [comment]
is it necessary to give another set of labels like:  bug / question / suggestion (enhancement)

**Comment by yorkie** [comment]
> is it necessary to give another set of labels like: bug / question / suggestion (enhancement)

They are the default labels in GitHub :)

**Comment by utkobe** [comment]
Okay, so I think this is enough

**Comment by yorkie** [comment]
The above labels are added, reopen it if anyone wants to change them :)
