### ISSUE TITLE
请问我的数据集在本地的话datasource要怎么设置呢？

### ISSUE THREAD

**Issue by tiancaidiyibu** [alibaba/pipcook#907]
"datasource": "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@b1f834c/scripts/image-classification/build/datasource.js?url=Users/adminx/Desktop/Ikki-study/iconcook/iconData/imgs.zip",

**Comment by FeelyChau** [comment]
```json
{
  "datasource": "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@b1f834c/scripts/image-classification/build/datasource.js?url=file:///Users/adminx/Desktop/Ikki-study/iconcook/iconData/imgs.zip"
}
```
试试这个

**Comment by tiancaidiyibu** [comment]
运行报这个错：run pipeline error: No data found in dataset pool.

这是我的pipeline设置
` {

    "specVersion": "2.0",
    "type": "ImageClassification",
    "datasource": "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@b1f834c/scripts/image-classification/build/datasource.js?url=file:///Users/adminx/Desktop/Ikki-study/iconcook/iconData/imgs.zip",
    "dataflow": [
      "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@b1f834c/scripts/image-classification/build/dataflow.js?size=224&size=224"
    ],
    "model": "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@b1f834c/scripts/image-classification/build/model.js",
    "options": {
      "framework": "tfjs@3.8",
      "train": {
        "epochs": 10
      }
    }
  }`
数据集结构是
`
- train
  -banquan
    - xx.jpg
    - ...
- validation
  - banquan
    - xx.jpg
    - ...
- test
  - banquan
    - xx.jpg
    - ...
`

**Comment by FeelyChau** [comment]
运行时加上 `-d` 参数，发一下运行日志，如果方便的话，最好发一个简化的数据集文件，我这边可以 debug 一下。

**Comment by tiancaidiyibu** [comment]
[imgs.zip](https://github.com/alibaba/pipcook/files/7770152/imgs.zip)

**Comment by FeelyChau** [comment]
> [imgs.zip](https://github.com/alibaba/pipcook/files/7770152/imgs.zip)

抱歉，如果是本地数据源的话，要指向目录，所以改成:
```json
{
  "datasource": "https://cdn.jsdelivr.net/gh/imgcook/pipcook-script@b1f834c/scripts/image-classification/build/datasource.js?url=file:///Users/adminx/Desktop/Ikki-study/iconcook/iconData/imgs/"
}
```
就好了。

**Comment by tiancaidiyibu** [comment]
![image](https://user-images.githubusercontent.com/50288014/147263048-23356c15-5117-4b40-b582-b95e6aa79c09.png)

**Comment by FeelyChau** [comment]
> ![image](https://user-images.githubusercontent.com/50288014/147263048-23356c15-5117-4b40-b582-b95e6aa79c09.png)

分类模型需要至少两个类别的图片，这个错误应该是数据源只包含了一个类别。

**Comment by tiancaidiyibu** [comment]
谢谢，已经搞定了。
