### ISSUE TITLE
'Python.h' file not found.

### ISSUE THREAD

**Issue by Txiaozhe** [alibaba/pipcook#97]
# Problem
for boa version is 0.5.2, it will throw an error: "'Python.h' file not found" when run 'npm install @pipcook/boa' or 'pipcook init':
<img width="1723" alt="36367E0F-D4CE-4C3D-BC62-B621F386A4E7" src="https://user-images.githubusercontent.com/14943539/79407732-4cfe1f80-7fcc-11ea-93a1-c294f471ff66.png">

# Solved
This version of boa(0.5.2) is dependents Python and Homebrew, so you need:
1、checking 'brew' was installed in your mac
2、checking 'Python3' was installed in your mac by run 
```shell
$ brew --prefix python\@3
```
<img width="317" alt="1586964262579_0CFED36D-DA99-417D-9920-EC49EBE3FA22" src="https://user-images.githubusercontent.com/14943539/79408028-f0e7cb00-7fcc-11ea-97fe-ba5c859fe611.png">

and you would found Python3 was installed, then checking:
```shell
$ `brew --prefix python\@3`/Frameworks/Python.framework/Versions/3.7/include/python3.7m
```
if it is not print effective info, it means you need install Python3 from
```shell
$ brew install python@3
```
right case:
<img width="750" alt="1" src="https://user-images.githubusercontent.com/14943539/79408371-b92d5300-7fcd-11ea-80f2-e0ed816e545a.png">

**Comment by yorkie** [comment]
Good shares, thank you @Txiaozhe :)
